BEGIN TRANSACTION;
INSERT INTO "stock" ("symbol", "name", "market_cap_group", "icb_supersector", "icb_industry")
  VALUES
  ('SVI','SVG CAPITAL PLC',1,'Financial Services','Financials'),
  ('MSLH','MARSHALLS PLC',1,'Construction & Materials','Industrials'),
  ('BAG','BARR (A.G.) PLC',1,'Food & Beverage','Consumer Goods'),
  ('KLR','KELLER GROUP PLC',1,'Construction & Materials','Industrials'),
  ('AO','AO WORLD PLC',1,'Retail','Consumer Services'),
  ('SCT','SOFTCAT PLC',1,'Technology','Technology'),
  ('SHAW','SHAWBROOK GROUP PLC',1,'Banks','Financials'),
  ('RTN','RESTAURANT GROUP PLC',1,'Travel & Leisure','Consumer Services'),
  ('DEB','DEBENHAMS PLC',1,'Retail','Consumer Services'),
  ('SHI','SIG PLC',1,'Industrial Goods & Services','Industrials'),
  ('PAY','PAYPOINT PLC',2,'Industrial Goods & Services','Industrials'),
  ('BHMG','BH MACRO LIMITED',2,'Financial Services','Financials'),
  ('PLP','POLYPIPE GROUP PLC',2,'Construction & Materials','Industrials'),
  ('RDI','REDEFINE INTERNATIONAL P.L.C.',2,'Real Estate','Financials'),
  ('HFD','HALFORDS GROUP PLC',2,'Retail','Consumer Services'),
  ('CLI','CLS HOLDINGS PLC',2,'Real Estate','Financials'),
  ('JII','JPMORGAN INDIAN INVESTMENT TRUST PLC',2,'Financial Services','Financials'),
  ('P2P','P2P GLOBAL INVE',2,'Financial Services','Financials'),
  ('PDL','PETRA DIAMONDS LIMITED',2,'Basic Resources','Basic Materials'),
  ('MTO','MITIE GROUP PLC',2,'Industrial Goods & Services','Industrials'),
  ('NTG','NORTHGATE PLC',3,'Industrial Goods & Services','Industrials'),
  ('CKN','CLARKSON PLC',3,'Industrial Goods & Services','Industrials'),
  ('SCIN','SCOTTISH INVESTMENT TRUST PLC',3,'Financial Services','Financials'),
  ('SMP','ST.MODWEN PROPERTIES PLC',3,'Real Estate','Financials'),
  ('MARS','MARSTON''S PLC',3,'Travel & Leisure','Consumer Services'),
  ('SNR','SENIOR PLC',3,'Industrial Goods & Services','Industrials'),
  ('WPCT','WOODFORD PATIENT CAPITAL TRUST PLC',3,'Financial Services','Financials'),
  ('PNL','PERSONAL ASSETS TRUST PLC',3,'Financial Services','Financials'),
  ('FEV','FIDELITY EUROPEAN VALUES PLC',3,'Financial Services','Financials'),
  ('NRR','NEWRIVER REIT PLC',3,'Real Estate','Financials'),
  ('ALD','ALDERMORE GROUP PLC',4,'Banks','Financials'),
  ('DCG','DAIRY CREST GROUP PLC',4,'Food & Beverage','Consumer Goods'),
  ('SAFE','SAFESTORE HOLDINGS PLC',4,'Real Estate','Financials'),
  ('FSJ','FISHER (JAMES) & SONS PLC',4,'Industrial Goods & Services','Industrials'),
  ('IBST','IBSTOCK PLC',4,'Construction & Materials','Industrials'),
  ('BTEM','BRITISH EMPIRE TRUST PLC',4,'Financial Services','Financials'),
  ('RNK','RANK GROUP PLC',4,'Travel & Leisure','Consumer Services'),
  ('GSS','GENESIS EMERGING MARKETS FUND LD',4,'Financial Services','Financials'),
  ('GOG','GO-AHEAD GROUP PLC',4,'Travel & Leisure','Consumer Services'),
  ('TMPL','TEMPLE BAR INVESTMENT TRUST PLC',4,'Financial Services','Financials'),
  ('HILS','HILL & SMITH HOLDINGS PLC',5,'Industrial Goods & Services','Industrials'),
  ('HTG','HUNTING PLC',5,'Oil & Gas','Oil & Gas'),
  ('HSTN','HANSTEEN HOLDINGS PLC',5,'Real Estate','Financials'),
  ('BRW','BREWIN DOLPHIN HOLDINGS PLC',5,'Financial Services','Financials'),
  ('PLI','PERPETUAL INCOME AND GROWTH INVESTMENT TRUST PLC',5,'Financial Services','Financials'),
  ('OSB','ONESAVINGS BANK PLC',5,'Financial Services','Financials'),
  ('UKW','GREENCOAT UK WIND PLC',5,'Financial Services','Financials'),
  ('MGAM','MORGAN ADVANCED MATERIALS PLC',5,'Industrial Goods & Services','Industrials'),
  ('ESUR','ESURE GROUP PLC',5,'Insurance','Financials'),
  ('IPO','IP GROUP PLC',5,'Financial Services','Financials'),
  ('CARD','CARD FACTORY PLC',6,'Retail','Consumer Services'),
  ('ALM','ALLIED MINDS PLC',6,'Financial Services','Financials'),
  ('TRIG','RENEWABLES',6,'Financial Services','Financials'),
  ('SNN','SANNE GROUP PLC',6,'Industrial Goods & Services','Industrials'),
  ('JMG','JPMORGAN EMERGING MARKETS INVESTMENT TRUST PLC',6,'Financial Services','Financials'),
  ('PETS','PETS AT HOME GROUP PLC',6,'Retail','Consumer Services'),
  ('SYNC','SYNCONA LIMITED',6,'Financial Services','Financials'),
  ('GCP','GCP INFRASTRUCTURE INVESTMENTS LIMITED',6,'Financial Services','Financials'),
  ('BNKR','BANKERS INVESTMENT TRUST PLC',6,'Financial Services','Financials'),
  ('NOG','NOSTRUM OIL & GAS PLC',6,'Oil & Gas','Oil & Gas'),
  ('CLLN','CARILLION PLC',7,'Industrial Goods & Services','Industrials'),
  ('FXPO','FERREXPO PLC',7,'Basic Resources','Basic Materials'),
  ('WIZZ','WIZZ AIR HOLDINGS PLC',7,'Travel & Leisure','Consumer Services'),
  ('CCC','COMPUTACENTER PLC',7,'Technology','Technology'),
  ('TRY','TR PROPERTY INVESTMENT TRUST PLC',7,'Financial Services','Financials'),
  ('AGR','ASSURA PLC',7,'Real Estate','Financials'),
  ('JAM','JPMORGAN AMERICAN INVESTMENT TRUST PLC',7,'Financial Services','Financials'),
  ('FDSA','FIDESSA GROUP PLC',7,'Technology','Technology'),
  ('TEP','TELECOM PLUS PLC',7,'Telecommunications','Telecommunications'),
  ('LMP','LONDONMETRIC PROPERTY PLC',7,'Real Estate','Financials'),
  ('HVPE','HARBOURVEST GLOBAL PRIVATE EQUITY LIMITED',8,'Financial Services','Financials'),
  ('VEC','VECTURA GROUP PLC',8,'Healthcare','Health Care'),
  ('GRG','GREGGS PLC',8,'Retail','Consumer Services'),
  ('JLG','JOHN LAING GROUP PLC',8,'Financial Services','Financials'),
  ('CSP','COUNTRYSIDE PROPERTIES PLC',8,'Personal & Household Goods','Consumer Goods'),
  ('ETO','ENTERTAINMENT ONE LTD.',8,'Media','Consumer Services'),
  ('NBLS','NB GLOBAL FLOATING RATE INCOME FUND LIMITED',8,'Financial Services','Financials'),
  ('FGT','FINSBURY GROWTH & INCOME TRUST PLC',8,'Financial Services','Financials'),
  ('FCSS','FIDELITY CHINA SPECIAL SITUATIONS PLC',8,'Financial Services','Financials'),
  ('MCS','MCCARTHY & STONE PLC',8,'Personal & Household Goods','Consumer Goods'),
  ('MAB','MITCHELLS & BUTLERS PLC',9,'Travel & Leisure','Consumer Services'),
  ('BVS','BOVIS HOMES GROUP PLC',9,'Personal & Household Goods','Consumer Goods'),
  ('GRI','GRAINGER PLC',9,'Real Estate','Financials'),
  ('GNS','GENUS PLC',9,'Healthcare','Health Care'),
  ('UKCM','UK COMMERCIAL PROPERTY TRUST LD',9,'Real Estate','Financials'),
  ('JDW','WETHERSPOON ( J.D.) PLC',9,'Travel & Leisure','Consumer Services'),
  ('RSE','RIVERSTONE ENERGY LIMITED',9,'Financial Services','Financials'),
  ('WWH','WORLDWIDE HEALTHCARE TRUST PLC',9,'Financial Services','Financials'),
  ('DJAN','DAEJAN HOLDINGS PLC',9,'Real Estate','Financials'),
  ('BGEO','BGEO GROUP PLC',9,'Banks','Financials'),
  ('FCPT','F&C COMMERCIAL PROPERTY TRUST LIMITED',10,'Real Estate','Financials'),
  ('ASL','ABERFORTH SMALLER COMPANIES TRUST PLC',10,'Financial Services','Financials'),
  ('RAT','RATHBONE BROTHERS PLC',10,'Financial Services','Financials'),
  ('BYG','BIG YELLOW GROUP PLC',10,'Real Estate','Financials'),
  ('PAG','PARAGON GROUP OF COMPANIES PLC',10,'Financial Services','Financials'),
  ('CWK','CRANSWICK PLC',10,'Food & Beverage','Consumer Goods'),
  ('ERM','EUROMONEY INSTITUTIONAL INVESTOR PLC',10,'Media','Consumer Services'),
  ('SGC','STAGECOACH GROUP PLC',10,'Travel & Leisure','Consumer Services'),
  ('SVS','SAVILLS PLC',10,'Real Estate','Financials'),
  ('SGP','SUPERGROUP PLC',10,'Personal & Household Goods','Consumer Goods'),
  ('DPLM','DIPLOMA PLC',11,'Industrial Goods & Services','Industrials'),
  ('KWE','KENNEDY WILSON EUROPE REAL ESTATE PLC',11,'Real Estate','Financials'),
  ('AVV','AVEVA GROUP PLC',11,'Technology','Technology'),
  ('JLIF','JOHN LAING INFRASTRUCTURE FUND LIMITED',11,'Financial Services','Financials'),
  ('VSVS','VESUVIUS PLC',11,'Industrial Goods & Services','Industrials'),
  ('TED','TED BAKER PLC',11,'Personal & Household Goods','Consumer Goods'),
  ('PCT','POLAR CAPITAL TECHNOLOGY TRUST PLC',11,'Financial Services','Financials'),
  ('GFRD','GALLIFORD TRY PLC',11,'Personal & Household Goods','Consumer Goods'),
  ('SOPH','SOPHOS GROUP PLC',11,'Technology','Technology'),
  ('ASCL','ASCENTIAL',11,'Financial Services','Financials'),
  ('CNE','CAIRN ENERGY PLC',12,'Oil & Gas','Oil & Gas'),
  ('DTY','DIGNITY PLC',12,'Retail','Consumer Services'),
  ('SRP','SERCO GROUP PLC',12,'Industrial Goods & Services','Industrials'),
  ('WKP','WORKSPACE GROUP PLC',12,'Real Estate','Financials'),
  ('DNLM','DUNELM GROUP PLC',12,'Retail','Consumer Services'),
  ('SPI','SPIRE HEALTHCARE GROUP PLC',12,'Healthcare','Health Care'),
  ('MNKS','MONKS INVESTMENT TRUST PLC',12,'Financial Services','Financials'),
  ('TCG','THOMAS COOK GROUP PLC',12,'Travel & Leisure','Consumer Services'),
  ('HOC','HOCHSCHILD MINING PLC',12,'Basic Resources','Basic Materials'),
  ('JRP','JRP GROUP PLC',12,'Insurance','Financials'),
  ('PZC','PZ CUSSONS PLC',13,'Personal & Household Goods','Consumer Goods'),
  ('ULE','ULTRA ELECTRONICS HOLDINGS PLC',13,'Industrial Goods & Services','Industrials'),
  ('CRST','CREST NICHOLSON HOLDINGS PLC',13,'Personal & Household Goods','Consumer Goods'),
  ('EDIN','EDINBURGH INVESTMENT TRUST PLC',13,'Financial Services','Financials'),
  ('PAGE','PAGEGROUP PLC',13,'Industrial Goods & Services','Industrials'),
  ('LRE','LANCASHIRE HOLDINGS LIMITED',13,'Insurance','Financials'),
  ('UTG','UNITE GROUP PLC',13,'Real Estate','Financials'),
  ('ELM','ELEMENTIS PLC',13,'Chemicals','Basic Materials'),
  ('KIE','KIER GROUP PLC',13,'Construction & Materials','Industrials'),
  ('CTY','CITY OF LONDON INVESTMENT TRUST PLC',13,'Financial Services','Financials'),
  ('ESNT','ESSENTRA PLC',14,'Industrial Goods & Services','Industrials'),
  ('DRX','DRAX GROUP PLC',14,'Utilities','Utilities'),
  ('FGP','FIRSTGROUP PLC',14,'Travel & Leisure','Consumer Services'),
  ('VM','VIRGIN MONEY HOLDINGS (UK) PLC',14,'Banks','Financials'),
  ('ATK','ATKINS (WS) PLC',14,'Industrial Goods & Services','Industrials'),
  ('GFTU','GRAFTON GROUP PLC',14,'Industrial Goods & Services','Industrials'),
  ('DPH','DECHRA PHARMACEUTICALS PLC',14,'Healthcare','Health Care'),
  ('MYI','MURRAY INTERNATIONAL TRUST PLC',14,'Financial Services','Financials'),
  ('BOY','BODYCOTE PLC',14,'Industrial Goods & Services','Industrials'),
  ('SYNT','SYNTHOMER PLC',14,'Chemicals','Basic Materials'),
  ('MLC','MILLENNIUM & COPTHORNE HOTELS PLC',15,'Travel & Leisure','Consumer Services'),
  ('HSTG','HASTINGS GROUP HOLDINGS PLC',15,'Insurance','Financials'),
  ('CLDN','CALEDONIA INVESTMENTS PLC',15,'Financial Services','Financials'),
  ('MRC','MERCANTILE INVESTMENT TRUST (THE) PLC',15,'Financial Services','Financials'),
  ('OCDO','OCADO GROUP PLC',15,'Retail','Consumer Services'),
  ('BRSN','BERENDSEN PLC',15,'Industrial Goods & Services','Industrials'),
  ('QQ','QINETIQ GROUP PLC',15,'Industrial Goods & Services','Industrials'),
  ('AA','AA PLC',15,'Industrial Goods & Services','Industrials'),
  ('BBOX','TRITAX BIG BOX REIT PLC',15,'Real Estate','Financials'),
  ('ZPLA','ZPG PLC',15,'Media','Consumer Services'),
  ('VCT','VICTREX PLC',16,'Chemicals','Basic Materials'),
  ('BVIC','BRITVIC PLC',16,'Food & Beverage','Consumer Goods'),
  ('TALK','TALKTALK TELECOM GROUP PLC',16,'Telecommunications','Telecommunications'),
  ('WTAN','WITAN INVESTMENT TRUST PLC',16,'Financial Services','Financials'),
  ('SPD','SPORTS DIRECT INTERNATIONAL PLC',16,'Retail','Consumer Services'),
  ('UDG','UDG HEALTHCARE PUBLIC LIMITED COMPANY',16,'Healthcare','Health Care'),
  ('AMFW','AMEC FOSTER WHEELER PLC',16,'Oil & Gas','Oil & Gas'),
  ('CINE','CINEWORLD GROUP PLC',16,'Travel & Leisure','Consumer Services'),
  ('INPP','INTERNATIONAL PUBLIC PARTNERSHIPS LD',16,'Financial Services','Financials'),
  ('MONY','MONEYSUPERMARKET.COM GROUP PLC',16,'Media','Consumer Services'),
  ('RDW','REDROW PLC',17,'Personal & Household Goods','Consumer Goods'),
  ('GNC','GREENCORE GROUP PLC',17,'Food & Beverage','Consumer Goods'),
  ('TEM','TEMPLETON EMERGING MARKETS INVESTMENT TRUST PLC',17,'Financial Services','Financials'),
  ('HSV','HOMESERVE PLC',17,'Industrial Goods & Services','Industrials'),
  ('NEX','NATIONAL EXPRESS GROUP PLC',17,'Travel & Leisure','Consumer Services'),
  ('ELTA','ELECTRA PRIVATE EQUITY PLC',17,'Financial Services','Financials'),
  ('SMWH','WH SMITH PLC',17,'Retail','Consumer Services'),
  ('DOM','DOMINO''S PIZZA GROUP PLC',17,'Travel & Leisure','Consumer Services'),
  ('BBY','BALFOUR BEATTY PLC',17,'Construction & Materials','Industrials'),
  ('JUP','JUPITER FUND MANAGEMENT PLC',17,'Financial Services','Financials'),
  ('IGG','IG GROUP HOLDINGS PLC',18,'Financial Services','Financials'),
  ('SSPG','SSP GROUP PLC',18,'Travel & Leisure','Consumer Services'),
  ('3IN','3I INFRASTRUCTURE PLC',18,'Financial Services','Financials'),
  ('CEY','CENTAMIN PLC',18,'Basic Resources','Basic Materials'),
  ('GVC','GVC HOLDINGS PLC',18,'Travel & Leisure','Consumer Services'),
  ('COB','COBHAM PLC',18,'Industrial Goods & Services','Industrials'),
  ('PAYS','PAYSAFE GROUP PLC',18,'Industrial Goods & Services','Industrials'),
  ('ICP','INTERMEDIATE CAPITAL GROUP PLC',18,'Financial Services','Financials'),
  ('GNK','GREENE KING PLC',18,'Travel & Leisure','Consumer Services'),
  ('ECM','ELECTROCOMPONENTS PLC',18,'Industrial Goods & Services','Industrials'),
  ('SAGA','SAGA PLC',19,'Retail','Consumer Services'),
  ('ROR','ROTORK PLC',19,'Industrial Goods & Services','Industrials'),
  ('ACA','ACACIA MINING PLC',19,'Basic Resources','Basic Materials'),
  ('NXG','NEX GROUP PLC',19,'Financial Services','Financials'),
  ('BTG','BTG PLC',19,'Healthcare','Health Care'),
  ('GPOR','GREAT PORTLAND ESTATES PLC',19,'Real Estate','Financials'),
  ('RSW','RENISHAW PLC',19,'Industrial Goods & Services','Industrials'),
  ('JLT','JARDINE LLOYD THOMPSON GROUP PLC',19,'Insurance','Financials'),
  ('WMH','WILLIAM HILL PLC',19,'Travel & Leisure','Consumer Services'),
  ('CBG','CLOSE BROTHERS GROUP PLC',19,'Financial Services','Financials'),
  ('BEZ','BEAZLEY PLC',20,'Insurance','Financials'),
  ('VED','VEDANTA RESOURCES PLC',20,'Basic Resources','Basic Materials'),
  ('CYBG','CYBG PLC',20,'Banks','Financials'),
  ('LCL','LADBROKES CORAL GROUP PLC',20,'Travel & Leisure','Consumer Services'),
  ('HAS','HAYS PLC',20,'Industrial Goods & Services','Industrials'),
  ('KAZ','KAZ MINERALS PLC',20,'Basic Resources','Basic Materials'),
  ('EMG','MAN GROUP PLC',20,'Financial Services','Financials'),
  ('TLW','TULLOW OIL PLC',20,'Oil & Gas','Oil & Gas'),
  ('CAPC','CAPITAL & COUNTIES PROPERTIES PLC',20,'Real Estate','Financials'),
  ('ASHM','ASHMORE GROUP PLC',20,'Financial Services','Financials'),
  ('HICL','HICL INFRASTRUCTURE COMPANY LD',21,'Financial Services','Financials'),
  ('INDV','INDIVIOR PLC',21,'Healthcare','Health Care'),
  ('HGG','HENDERSON GROUP PLC',21,'Financial Services','Financials'),
  ('SHB','SHAFTESBURY PLC',21,'Real Estate','Financials'),
  ('IWG','IWG PLC',21,'Industrial Goods & Services','Industrials'),
  ('HWDN','HOWDEN JOINERY GROUP PLC',21,'Industrial Goods & Services','Industrials'),
  ('AGK','AGGREKO PLC',21,'Industrial Goods & Services','Industrials'),
  ('TLPR','TP ICAP PLC',21,'Financial Services','Financials'),
  ('MTRO','METRO BANK PLC',21,'Banks','Financials'),
  ('PTEC','PLAYTECH PLC',21,'Travel & Leisure','Consumer Services'),
  ('WG','WOOD GROUP (JOHN) PLC',22,'Oil & Gas','Oil & Gas'),
  ('SXS','SPECTRIS PLC',22,'Industrial Goods & Services','Industrials'),
  ('UBM','UBM PLC',22,'Media','Consumer Services'),
  ('RCP','RIT CAPITAL PARTNERS PLC',22,'Financial Services','Financials'),
  ('BME','B&M EUROPEAN VALUE RETAIL S.A.',22,'Retail','Consumer Services'),
  ('PHNX','PHOENIX GROUP HOLDINGS',22,'Insurance','Financials'),
  ('PFC','PETROFAC LIMITED',22,'Oil & Gas','Oil & Gas'),
  ('FRCL','FOREIGN & COLONIAL INVESTMENT TRUST PLC',22,'Financial Services','Financials'),
  ('HSX','HISCOX LTD',22,'Insurance','Financials'),
  ('DLN','DERWENT LONDON PLC',22,'Real Estate','Financials'),
  ('BBA','BBA AVIATION PLC',23,'Industrial Goods & Services','Industrials'),
  ('INCH','INCHCAPE PLC',23,'Retail','Consumer Services'),
  ('BWY','BELLWAY PLC',23,'Personal & Household Goods','Consumer Goods'),
  ('ISAT','INMARSAT PLC',23,'Telecommunications','Telecommunications'),
  ('ATST','ALLIANCE TRUST PLC',23,'Financial Services','Financials'),
  ('EVR','EVRAZ PLC',23,'Basic Resources','Basic Materials'),
  ('SPX','SPIRAX-SARCO ENGINEERING PLC',23,'Industrial Goods & Services','Industrials'),
  ('IMI','IMI PLC',23,'Industrial Goods & Services','Industrials'),
  ('JE','JUST EAT PLC',23,'Retail','Consumer Services'),
  ('JD','JD SPORTS FASHION PLC',23,'Retail','Consumer Services'),
  ('TATE','TATE & LYLE PLC',24,'Food & Beverage','Consumer Goods'),
  ('DC','DIXONS CARPHONE PLC',24,'Retail','Consumer Services'),
  ('BOK','BOOKER GROUP PLC',24,'Retail','Consumer Services'),
  ('NMC','NMC HEALTH PLC',24,'Healthcare','Health Care'),
  ('PNN','PENNON GROUP PLC',24,'Utilities','Utilities'),
  ('ADN','ABERDEEN ASSET MANAGEMENT PLC',24,'Financial Services','Financials'),
  ('MGGT','MEGGITT PLC',24,'Industrial Goods & Services','Industrials'),
  ('RMV','RIGHTMOVE PLC',24,'Media','Consumer Services'),
  ('HLMA','HALMA PLC',24,'Industrial Goods & Services','Industrials'),
  ('CPI','CAPITA PLC',24,'Industrial Goods & Services','Industrials'),
  ('EZJ','EASYJET PLC',25,'Travel & Leisure','Consumer Services'),
  ('RPC','RPC GROUP PLC',25,'Industrial Goods & Services','Industrials'),
  ('INVP','INVESTEC PLC',25,'Financial Services','Financials'),
  ('TPK','TRAVIS PERKINS PLC',25,'Industrial Goods & Services','Industrials'),
  ('AUTO','AUTO TRADER GROUP PLC',25,'Media','Consumer Services'),
  ('INTU','INTU PROPERTIES PLC',25,'Real Estate','Financials'),
  ('GFS','G4S PLC',25,'Industrial Goods & Services','Industrials'),
  ('BKG','BERKELEY GROUP HOLDINGS (THE) PLC',25,'Personal & Household Goods','Consumer Goods'),
  ('SGRO','SEGRO PLC',25,'Real Estate','Financials'),
  ('WEIR','WEIR GROUP PLC',25,'Industrial Goods & Services','Industrials'),
  ('POLY','POLYMETAL INTERNATIONAL PLC',26,'Basic Resources','Basic Materials'),
  ('RMG','ROYAL MAIL PLC',26,'Industrial Goods & Services','Industrials'),
  ('SMDS','SMITH (DS) PLC',26,'Industrial Goods & Services','Industrials'),
  ('PFG','PROVIDENT FINANCIAL PLC',26,'Financial Services','Financials'),
  ('RTO','RENTOKIL INITIAL PLC',26,'Industrial Goods & Services','Industrials'),
  ('CRDA','CRODA INTERNATIONAL PLC',26,'Chemicals','Basic Materials'),
  ('CTEC','CONVATEC GROUP PLC',26,'Healthcare','Health Care'),
  ('HMSO','HAMMERSON PLC',26,'Real Estate','Financials'),
  ('SMT','SCOTTISH MORTGAGE INVESTMENT TRUST PLC',26,'Financial Services','Financials'),
  ('DLG','DIRECT LINE INSURANCE GROUP PLC',26,'Insurance','Financials'),
  ('BAB','BABCOCK INTERNATIONAL GROUP PLC',27,'Industrial Goods & Services','Industrials'),
  ('MERL','MERLIN ENTERTAINMENTS PLC',27,'Travel & Leisure','Consumer Services'),
  ('MCRO','MICRO FOCUS INTERNATIONAL PLC',27,'Technology','Technology'),
  ('SKG','SMURFIT KAPPA GROUP PLC',27,'Industrial Goods & Services','Industrials'),
  ('BDEV','BARRATT DEVELOPMENTS PLC',27,'Personal & Household Goods','Consumer Goods'),
  ('HIK','HIKMA PHARMACEUTICALS PLC',27,'Healthcare','Health Care'),
  ('ADM','ADMIRAL GROUP PLC',27,'Insurance','Financials'),
  ('WPG','WORLDPAY GROUP PLC',27,'Industrial Goods & Services','Industrials'),
  ('MKS','MARKS AND SPENCER GROUP PLC',27,'Retail','Consumer Services'),
  ('MDC','MEDICLINIC INTERNATIONAL PLC',27,'Healthcare','Health Care'),
  ('SVT','SEVERN TRENT PLC',28,'Utilities','Utilities'),
  ('INF','INFORMA PLC',28,'Media','Consumer Services'),
  ('PSON','PEARSON PLC',28,'Media','Consumer Services'),
  ('STJ','ST. JAMES''S PLACE PLC',28,'Insurance','Financials'),
  ('NXT','NEXT PLC',28,'Retail','Consumer Services'),
  ('MRW','MORRISON (WM) SUPERMARKETS PLC',28,'Retail','Consumer Services'),
  ('ITRK','INTERTEK GROUP PLC',28,'Industrial Goods & Services','Industrials'),
  ('SBRY','SAINSBURY (J) PLC',28,'Retail','Consumer Services'),
  ('TW','TAYLOR WIMPEY PLC',28,'Personal & Household Goods','Consumer Goods'),
  ('SMIN','SMITHS GROUP PLC',28,'Industrial Goods & Services','Industrials'),
  ('JMAT','JOHNSON MATTHEY PLC',29,'Chemicals','Basic Materials'),
  ('DCC','DCC PLC',29,'Industrial Goods & Services','Industrials'),
  ('GKN','GKN PLC',29,'Automobiles & Parts','Consumer Goods'),
  ('RSA','RSA INSURANCE GROUP PLC',29,'Insurance','Financials'),
  ('HL','HARGREAVES LANSDOWN PLC',29,'Financial Services','Financials'),
  ('BLND','BRITISH LAND COMPANY PLC',29,'Real Estate','Financials'),
  ('PSN','PERSIMMON PLC',29,'Personal & Household Goods','Consumer Goods'),
  ('UU','UNITED UTILITIES GROUP PLC',29,'Utilities','Utilities'),
  ('TUI','TUI AG',29,'Travel & Leisure','Consumer Services'),
  ('III','3I GROUP PLC',29,'Financial Services','Financials'),
  ('MNDI','MONDI PLC',30,'Basic Resources','Basic Materials'),
  ('SGE','SAGE GROUP PLC',30,'Technology','Technology'),
  ('WTB','WHITBREAD PLC',30,'Travel & Leisure','Consumer Services'),
  ('RRS','RANDGOLD RESOURCES LD',30,'Basic Resources','Basic Materials'),
  ('CCH','COCA-COLA HBC AG',30,'Food & Beverage','Consumer Goods'),
  ('SL','STANDARD LIFE PLC',30,'Insurance','Financials'),
  ('KGF','KINGFISHER PLC',30,'Retail','Consumer Services'),
  ('PPB','PADDY POWER BETFAIR PLC',30,'Travel & Leisure','Consumer Services'),
  ('IHG','INTERCONTINENTAL HOTELS GROUP PLC',30,'Travel & Leisure','Consumer Services'),
  ('BNZL','BUNZL PLC',30,'Industrial Goods & Services','Industrials'),
  ('BRBY','BURBERRY GROUP PLC',31,'Personal & Household Goods','Consumer Goods'),
  ('ANTO','ANTOFAGASTA PLC',31,'Basic Resources','Basic Materials'),
  ('ITV','ITV PLC',31,'Media','Consumer Services'),
  ('SDR','SCHRODERS PLC',31,'Financial Services','Financials'),
  ('AHT','ASHTEAD GROUP PLC',31,'Industrial Goods & Services','Industrials'),
  ('LAND','LAND SECURITIES GROUP PLC',31,'Real Estate','Financials'),
  ('CCL','CARNIVAL PLC',31,'Travel & Leisure','Consumer Services'),
  ('SN','SMITH & NEPHEW PLC',31,'Healthcare','Health Care'),
  ('OML','OLD MUTUAL PLC',31,'Insurance','Financials'),
  ('LSE','LONDON STOCK EXCHANGE GROUP PLC',31,'Financial Services','Financials'),
  ('FRES','FRESNILLO PLC',32,'Basic Resources','Basic Materials'),
  ('IAG','INTERNATIONAL CONSOLIDATED AIRLINES GROUP S.A.',32,'Travel & Leisure','Consumer Services'),
  ('WOS','WOLSELEY PLC',32,'Industrial Goods & Services','Industrials'),
  ('CNA','CENTRICA PLC',32,'Utilities','Utilities'),
  ('RR','ROLLS-ROYCE HOLDINGS PLC',32,'Industrial Goods & Services','Industrials'),
  ('LGEN','LEGAL & GENERAL GROUP PLC',32,'Insurance','Financials'),
  ('EXPN','EXPERIAN PLC',32,'Industrial Goods & Services','Industrials'),
  ('TSCO','TESCO PLC',32,'Retail','Consumer Services'),
  ('SSE','SSE PLC',32,'Utilities','Utilities'),
  ('REL','RELX PLC',32,'Media','Consumer Services'),
  ('SKY','SKY PLC',33,'Media','Consumer Services'),
  ('AAL','ANGLO AMERICAN PLC',33,'Basic Resources','Basic Materials'),
  ('BA','BAE SYSTEMS PLC',33,'Industrial Goods & Services','Industrials'),
  ('AV','AVIVA PLC',33,'Insurance','Financials'),
  ('ABF','ASSOCIATED BRITISH FOODS PLC',33,'Food & Beverage','Consumer Goods'),
  ('CRH','CRH PLC',33,'Construction & Materials','Industrials'),
  ('STAN','STANDARD CHARTERED PLC',33,'Banks','Financials'),
  ('WPP','WPP PLC',33,'Media','Consumer Services'),
  ('CPG','COMPASS GROUP PLC',33,'Travel & Leisure','Consumer Services'),
  ('BLT','BHP BILLITON PLC',33,'Basic Resources','Basic Materials'),
  ('RBS','ROYAL BANK OF SCOTLAND GROUP PLC',34,'Banks','Financials'),
  ('BT_A','BT GROUP PLC',34,'Telecommunications','Telecommunications'),
  ('IMB','IMPERIAL BRANDS PLC',34,'Personal & Household Goods','Consumer Goods'),
  ('NG','NATIONAL GRID PLC',34,'Utilities','Utilities'),
  ('BARC','BARCLAYS PLC',34,'Banks','Financials'),
  ('PRU','PRUDENTIAL PLC',34,'Insurance','Financials'),
  ('SHP','SHIRE PLC',34,'Healthcare','Health Care'),
  ('RIO','RIO TINTO PLC',34,'Basic Resources','Basic Materials'),
  ('GLEN','GLENCORE PLC',34,'Basic Resources','Basic Materials'),
  ('LLOY','LLOYDS BANKING GROUP PLC',34,'Banks','Financials'),
  ('ULVR','UNILEVER PLC',35,'Personal & Household Goods','Consumer Goods'),
  ('RB','RECKITT BENCKISER GROUP PLC',35,'Personal & Household Goods','Consumer Goods'),
  ('VOD','VODAFONE GROUP PLC',35,'Telecommunications','Telecommunications'),
  ('DGE','DIAGEO PLC',35,'Food & Beverage','Consumer Goods'),
  ('AZN','ASTRAZENECA PLC',35,'Healthcare','Health Care'),
  ('GSK','GLAXOSMITHKLINE PLC',35,'Healthcare','Health Care'),
  ('RDSB','RDS ''B''',35,'Oil & Gas','Oil & Gas'),
  ('BP','BP PLC',35,'Oil & Gas','Oil & Gas'),
  ('BATS','BRITISH AMERICAN TOBACCO PLC',35,'Personal & Household Goods','Consumer Goods'),
  ('RDSA','RDS ''A''',35,'Oil & Gas','Oil & Gas'),
  ('HSBA','HSBC HOLDINGS PLC',35,'Banks','Financials');
COMMIT;